/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TradeInRouteImport } from './routes/trade-in'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as SectorsRouteImport } from './routes/sectors'
import { Route as ScannerRouteImport } from './routes/scanner'
import { Route as RewardsRouteImport } from './routes/rewards'
import { Route as PickupsRouteImport } from './routes/pickups'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as MapRouteImport } from './routes/map'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as EventsRouteImport } from './routes/events'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as AdminDashboardRouteImport } from './routes/admin-dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SectorsSectorIdRouteImport } from './routes/sectors.$sectorId'
import { Route as InstitutionsInstIdRouteImport } from './routes/institutions.$instId'
import { Route as AuthSignupRouteImport } from './routes/auth.signup'
import { Route as AuthLoginRouteImport } from './routes/auth.login'

const TradeInRoute = TradeInRouteImport.update({
  id: '/trade-in',
  path: '/trade-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const SectorsRoute = SectorsRouteImport.update({
  id: '/sectors',
  path: '/sectors',
  getParentRoute: () => rootRouteImport,
} as any)
const ScannerRoute = ScannerRouteImport.update({
  id: '/scanner',
  path: '/scanner',
  getParentRoute: () => rootRouteImport,
} as any)
const RewardsRoute = RewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => rootRouteImport,
} as any)
const PickupsRoute = PickupsRouteImport.update({
  id: '/pickups',
  path: '/pickups',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin-dashboard',
  path: '/admin-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SectorsSectorIdRoute = SectorsSectorIdRouteImport.update({
  id: '/$sectorId',
  path: '/$sectorId',
  getParentRoute: () => SectorsRoute,
} as any)
const InstitutionsInstIdRoute = InstitutionsInstIdRouteImport.update({
  id: '/institutions/$instId',
  path: '/institutions/$instId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin-dashboard': typeof AdminDashboardRoute
  '/community': typeof CommunityRoute
  '/dashboard': typeof DashboardRoute
  '/events': typeof EventsRoute
  '/knowledge': typeof KnowledgeRoute
  '/leaderboard': typeof LeaderboardRoute
  '/map': typeof MapRoute
  '/marketplace': typeof MarketplaceRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/pickups': typeof PickupsRoute
  '/rewards': typeof RewardsRoute
  '/scanner': typeof ScannerRoute
  '/sectors': typeof SectorsRouteWithChildren
  '/security': typeof SecurityRoute
  '/settings': typeof SettingsRoute
  '/trade-in': typeof TradeInRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/institutions/$instId': typeof InstitutionsInstIdRoute
  '/sectors/$sectorId': typeof SectorsSectorIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-dashboard': typeof AdminDashboardRoute
  '/community': typeof CommunityRoute
  '/dashboard': typeof DashboardRoute
  '/events': typeof EventsRoute
  '/knowledge': typeof KnowledgeRoute
  '/leaderboard': typeof LeaderboardRoute
  '/map': typeof MapRoute
  '/marketplace': typeof MarketplaceRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/pickups': typeof PickupsRoute
  '/rewards': typeof RewardsRoute
  '/scanner': typeof ScannerRoute
  '/sectors': typeof SectorsRouteWithChildren
  '/security': typeof SecurityRoute
  '/settings': typeof SettingsRoute
  '/trade-in': typeof TradeInRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/institutions/$instId': typeof InstitutionsInstIdRoute
  '/sectors/$sectorId': typeof SectorsSectorIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin-dashboard': typeof AdminDashboardRoute
  '/community': typeof CommunityRoute
  '/dashboard': typeof DashboardRoute
  '/events': typeof EventsRoute
  '/knowledge': typeof KnowledgeRoute
  '/leaderboard': typeof LeaderboardRoute
  '/map': typeof MapRoute
  '/marketplace': typeof MarketplaceRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/pickups': typeof PickupsRoute
  '/rewards': typeof RewardsRoute
  '/scanner': typeof ScannerRoute
  '/sectors': typeof SectorsRouteWithChildren
  '/security': typeof SecurityRoute
  '/settings': typeof SettingsRoute
  '/trade-in': typeof TradeInRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/institutions/$instId': typeof InstitutionsInstIdRoute
  '/sectors/$sectorId': typeof SectorsSectorIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin-dashboard'
    | '/community'
    | '/dashboard'
    | '/events'
    | '/knowledge'
    | '/leaderboard'
    | '/map'
    | '/marketplace'
    | '/messages'
    | '/notifications'
    | '/pickups'
    | '/rewards'
    | '/scanner'
    | '/sectors'
    | '/security'
    | '/settings'
    | '/trade-in'
    | '/auth/login'
    | '/auth/signup'
    | '/institutions/$instId'
    | '/sectors/$sectorId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-dashboard'
    | '/community'
    | '/dashboard'
    | '/events'
    | '/knowledge'
    | '/leaderboard'
    | '/map'
    | '/marketplace'
    | '/messages'
    | '/notifications'
    | '/pickups'
    | '/rewards'
    | '/scanner'
    | '/sectors'
    | '/security'
    | '/settings'
    | '/trade-in'
    | '/auth/login'
    | '/auth/signup'
    | '/institutions/$instId'
    | '/sectors/$sectorId'
  id:
    | '__root__'
    | '/'
    | '/admin-dashboard'
    | '/community'
    | '/dashboard'
    | '/events'
    | '/knowledge'
    | '/leaderboard'
    | '/map'
    | '/marketplace'
    | '/messages'
    | '/notifications'
    | '/pickups'
    | '/rewards'
    | '/scanner'
    | '/sectors'
    | '/security'
    | '/settings'
    | '/trade-in'
    | '/auth/login'
    | '/auth/signup'
    | '/institutions/$instId'
    | '/sectors/$sectorId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  CommunityRoute: typeof CommunityRoute
  DashboardRoute: typeof DashboardRoute
  EventsRoute: typeof EventsRoute
  KnowledgeRoute: typeof KnowledgeRoute
  LeaderboardRoute: typeof LeaderboardRoute
  MapRoute: typeof MapRoute
  MarketplaceRoute: typeof MarketplaceRoute
  MessagesRoute: typeof MessagesRoute
  NotificationsRoute: typeof NotificationsRoute
  PickupsRoute: typeof PickupsRoute
  RewardsRoute: typeof RewardsRoute
  ScannerRoute: typeof ScannerRoute
  SectorsRoute: typeof SectorsRouteWithChildren
  SecurityRoute: typeof SecurityRoute
  SettingsRoute: typeof SettingsRoute
  TradeInRoute: typeof TradeInRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
  InstitutionsInstIdRoute: typeof InstitutionsInstIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trade-in': {
      id: '/trade-in'
      path: '/trade-in'
      fullPath: '/trade-in'
      preLoaderRoute: typeof TradeInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sectors': {
      id: '/sectors'
      path: '/sectors'
      fullPath: '/sectors'
      preLoaderRoute: typeof SectorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scanner': {
      id: '/scanner'
      path: '/scanner'
      fullPath: '/scanner'
      preLoaderRoute: typeof ScannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rewards': {
      id: '/rewards'
      path: '/rewards'
      fullPath: '/rewards'
      preLoaderRoute: typeof RewardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pickups': {
      id: '/pickups'
      path: '/pickups'
      fullPath: '/pickups'
      preLoaderRoute: typeof PickupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-dashboard': {
      id: '/admin-dashboard'
      path: '/admin-dashboard'
      fullPath: '/admin-dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sectors/$sectorId': {
      id: '/sectors/$sectorId'
      path: '/$sectorId'
      fullPath: '/sectors/$sectorId'
      preLoaderRoute: typeof SectorsSectorIdRouteImport
      parentRoute: typeof SectorsRoute
    }
    '/institutions/$instId': {
      id: '/institutions/$instId'
      path: '/institutions/$instId'
      fullPath: '/institutions/$instId'
      preLoaderRoute: typeof InstitutionsInstIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SectorsRouteChildren {
  SectorsSectorIdRoute: typeof SectorsSectorIdRoute
}

const SectorsRouteChildren: SectorsRouteChildren = {
  SectorsSectorIdRoute: SectorsSectorIdRoute,
}

const SectorsRouteWithChildren =
  SectorsRoute._addFileChildren(SectorsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  CommunityRoute: CommunityRoute,
  DashboardRoute: DashboardRoute,
  EventsRoute: EventsRoute,
  KnowledgeRoute: KnowledgeRoute,
  LeaderboardRoute: LeaderboardRoute,
  MapRoute: MapRoute,
  MarketplaceRoute: MarketplaceRoute,
  MessagesRoute: MessagesRoute,
  NotificationsRoute: NotificationsRoute,
  PickupsRoute: PickupsRoute,
  RewardsRoute: RewardsRoute,
  ScannerRoute: ScannerRoute,
  SectorsRoute: SectorsRouteWithChildren,
  SecurityRoute: SecurityRoute,
  SettingsRoute: SettingsRoute,
  TradeInRoute: TradeInRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
  InstitutionsInstIdRoute: InstitutionsInstIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
